FROM rust:1-slim-buster as builder
WORKDIR app
COPY . .
RUN apt-get -y update
RUN apt-get -y install libpq-dev
RUN cargo build --release --bin miningpool-observer-daemon

FROM debian:buster-slim as runtime
RUN apt-get -y update
RUN apt-get -y install libpq-dev

COPY contrib/docker/entrypoint-daemon.sh /
WORKDIR /app
COPY --from=builder /app/target/release/miningpool-observer-daemon /app/daemon

ENV CONFIG_FILE=/app/daemon-config.toml
ENTRYPOINT ["/entrypoint-daemon.sh"]
CMD ["/app/daemon"]
