name: docker-images

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

defaults:
  run:
    working-directory: ./

jobs:
  build-and-push-daemon-container-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: checkout repo
        uses: actions/checkout@v2
      -
        name: Build miningpool-observer-daemon and push
        id: docker_build_daemon
        uses: docker/build-push-action@v2
        with:
          file: contrib/docker/Dockerfile.daemon
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: b10c/miningpool-observer:daemon-latest
  build-and-push-web-container-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: checkout repo
        uses: actions/checkout@v2
      -
        name: Build miningpool-observer-web and push
        id: docker_build_web
        uses: docker/build-push-action@v2
        with:
          file: contrib/docker/Dockerfile.web
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: b10c/miningpool-observer:web-latest
